/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateCookBookArgs } from "./CreateCookBookArgs";
import { UpdateCookBookArgs } from "./UpdateCookBookArgs";
import { DeleteCookBookArgs } from "./DeleteCookBookArgs";
import { CookBookFindManyArgs } from "./CookBookFindManyArgs";
import { CookBookFindUniqueArgs } from "./CookBookFindUniqueArgs";
import { CookBook } from "./CookBook";
import { CookBookService } from "../cookBook.service";

@graphql.Resolver(() => CookBook)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CookBookResolverBase {
  constructor(
    protected readonly service: CookBookService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CookBook",
    action: "read",
    possession: "any",
  })
  async _cookBooksMeta(
    @graphql.Args() args: CookBookFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [CookBook])
  @nestAccessControl.UseRoles({
    resource: "CookBook",
    action: "read",
    possession: "any",
  })
  async cookBooks(
    @graphql.Args() args: CookBookFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CookBook[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "CookBook",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => CookBook, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CookBook",
    action: "read",
    possession: "own",
  })
  async cookBook(
    @graphql.Args() args: CookBookFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CookBook | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "CookBook",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => CookBook)
  @nestAccessControl.UseRoles({
    resource: "CookBook",
    action: "create",
    possession: "any",
  })
  async createCookBook(
    @graphql.Args() args: CreateCookBookArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CookBook> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "CookBook",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CookBook"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => CookBook)
  @nestAccessControl.UseRoles({
    resource: "CookBook",
    action: "update",
    possession: "any",
  })
  async updateCookBook(
    @graphql.Args() args: UpdateCookBookArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CookBook | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "CookBook",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CookBook"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CookBook)
  @nestAccessControl.UseRoles({
    resource: "CookBook",
    action: "delete",
    possession: "any",
  })
  async deleteCookBook(
    @graphql.Args() args: DeleteCookBookArgs
  ): Promise<CookBook | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
